version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "honey-bees"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-acdvo2q8xy6z"
s3_prefix = "honey-bees"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
